application: phalanges
version: 1
runtime: python
api_version: 1

handlers:
- url: /api
  script: api.py

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static

- url: /.*
  script: not_found.py